name: Deploy Website to InfinityFree

on:
  push:
    branches:
      - main  # Pastikan ini sesuai dengan cabang utama Anda (main atau master)

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/  # Ganti dengan direktori spesifik domain Anda jika menggunakan addon domain
